# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SakuraDemo_OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'SSZipArchive'
  # Pods for SakuraDemo_OC

  target 'SakuraDemo_OCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SakuraDemo_OCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
